### PR TITLE
General consistency changes

### PR DESCRIPTION
**Pull request by AwesomestCode**

### CODE REVIEW

**Comment by rom1504** [comment]
what is this doing

**Comment by AwesomestCode** [comment]
https://discord.com/channels/413438066984747026/876588959378055208/882026776497369130

**Comment by AwesomestCode** [comment]
Question, why was this closed? Believe this was for the convo in Discord

**Comment by rom1504** [comment]
you did not provide an explanation on what it is doing, the discord link is unclear

**Pull request closed without merging**
