### PR TITLE
Support all 1.20 builds

### PR DESCRIPTION
**Pull request by test137E29B**
Adds support for the 1.20, 1.20.1 and 1.20.2 servers. Doubt anything other than 1.20.2 is really neeeded though.

### CODE REVIEW

**Comment by rom1504** [comment]
Hey. Let's add only 1.20.2

**Comment by test137E29B** [comment]
> Hey. Let's add only 1.20.2

Have removed 1.20 and 1.20.1 - let me know if anything else is needed :)

**Comment by rom1504** [comment]
Thanks

**Pull request merged**
