### PR TITLE
Support 1.21.1

### PR DESCRIPTION
**Pull request by Icyadam14**
This will close issue #29. I just ran [image_names.js](https://github.com/PrismarineJS/minecraft-jar-extractor/blob/master/image_names.js). I did not do any testing with the extracted data.

### CODE REVIEW

**Comment by rom1504** [comment]
1.21.1 folder needs to go in data/

**Comment by Icyadam14** [comment]
Whoops! I moved the 1.21.1 folder and updated the README.

**Comment by rom1504** [comment]
Thanks

**Comment by rom1504** [comment]
Can you update https://github.com/PrismarineJS/node-minecraft-assets/blob/master/index.js#L131 as well in a PR in that repo ?

**Comment by Icyadam14** [comment]
> Can you update https://github.com/PrismarineJS/node-minecraft-assets/blob/master/index.js#L131 as well in a PR in that repo ?

Done: https://github.com/PrismarineJS/node-minecraft-assets/pull/36

**Comment by rom1504** [comment]
Thanks, and finally this https://github.com/PrismarineJS/prismarine-viewer/blob/master/viewer/lib/version.js#L1

**Comment by Icyadam14** [comment]
> Thanks, and finally this https://github.com/PrismarineJS/prismarine-viewer/blob/master/viewer/lib/version.js#L1

Here's the PR: https://github.com/PrismarineJS/prismarine-viewer/pull/439

**Pull request merged**
